projects:
  outfits:
    schemaPath: amplify/backend/api/outfits/build/schema.graphql
    includes:
      - ./graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: ./API.ts
        docsFilePath: ./graphql
        region: us-west-2
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
